### PR TITLE
Bug/127 Fixed bug that hid failing tests and fixed failing tests

### LINKED ISSUE #127: Tests broken
Du to a bug in [shurefire 3.0.0-M4](https://issues.apache.org/jira/browse/SUREFIRE-1688) test failures were ignored.

By that some tests failed unrecogniced

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #127

### CODE REVIEW

File: src/test/java/com/exasol/adapter/document/DynamodbVsExasolTestDatabaseBuilder.java [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+                .append(ADAPTER_SCHEMA).append(".").append(UdfRequestDispatcher.UDF_PREFIX + "DYNAMO_DB").append("(")
+                .append(AbstractDataLoaderUdf.PARAMETER_DOCUMENT_FETCHER).append(" VARCHAR(2000000), ")
+                .append(AbstractDataLoaderUdf.PARAMETER_REMOTE_TABLE_QUERY).append(" VARCHAR(2000000), ")
+                .append(AbstractDataLoaderUdf.PARAMETER_CONNECTION_NAME).append(" VARCHAR(500)) EMITS(...) AS\n");
+        addDebuggerOptions(statementBuilder, true);
+        statementBuilder.append("    %scriptclass ").append(UdfRequestDispatcher.class.getName()).append(";\n");
+        statementBuilder.append("    %jar /buckets/bfsdefault/default/").append(VIRTUAL_SCHEMAS_JAR_NAME_AND_VERSION)
+                .append(";\n");
+        statementBuilder.append("/");
+        final String sql = statementBuilder.toString();
```
Comment (AnastasiiaSergienko) [inline src/test/java/com/exasol/adapter/document/DynamodbVsExasolTestDatabaseBuilder.java:41]: It's very hard to read this builder concatenations. Maybe it's better to use just a string instead?

File: src/test/java/com/exasol/adapter/document/DynamodbVsExasolTestDatabaseBuilder.java [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+        uploadJacocoAgent();
+    }
+
+    public void createUdf() throws SQLException {// TODO make DynamoDB independent
+        final StringBuilder statementBuilder = new StringBuilder("CREATE OR REPLACE JAVA SET SCRIPT ")
+                .append(ADAPTER_SCHEMA).append(".").append(UdfRequestDispatcher.UDF_PREFIX + "DYNAMO_DB").append("(")
+                .append(AbstractDataLoaderUdf.PARAMETER_DOCUMENT_FETCHER).append(" VARCHAR(2000000), ")
+                .append(AbstractDataLoaderUdf.PARAMETER_REMOTE_TABLE_QUERY).append(" VARCHAR(2000000), ")
+                .append(AbstractDataLoaderUdf.PARAMETER_CONNECTION_NAME).append(" VARCHAR(500)) EMITS(...) AS\n");
+        addDebuggerOptions(statementBuilder, true);
```
Comment (AnastasiiaSergienko) [inline src/test/java/com/exasol/adapter/document/DynamodbVsExasolTestDatabaseBuilder.java:36]: It's usually not a good idea to send a builder inside and make some magic in a black box. It's better to return a String and append it ouside

**Review by AnastasiiaSergienko — CHANGES_REQUESTED** [review]

File: src/test/java/com/exasol/adapter/document/DynamodbVsExasolTestDatabaseBuilder.java (hunk 2 above)
Comment (jakobbraun) [reply src/test/java/com/exasol/adapter/document/DynamodbVsExasolTestDatabaseBuilder.java:36]: I totally agree, the issue is just, that `addDebuggerOptions` is part of the document-vs so I would have to create another release for that...

File: src/test/java/com/exasol/adapter/document/DynamodbVsExasolTestDatabaseBuilder.java (hunk 1 above)
Comment (jakobbraun) [reply src/test/java/com/exasol/adapter/document/DynamodbVsExasolTestDatabaseBuilder.java:41]: What exactly would you suggest?
I learned that += leads to bad performance...
Using + inside of an append leads to sonar warnings which suggest using the builder instead.

Comment (AnastasiiaSergienko) [reply src/test/java/com/exasol/adapter/document/DynamodbVsExasolTestDatabaseBuilder.java:41]: It a test, so such a small performance optimization doesn't really matter here  and sometimes you can ignore this warning if it significantly improves readability

File: src/test/java/com/exasol/adapter/document/DynamodbVsExasolTestDatabaseBuilder.java (hunk 2 above)
Comment (AnastasiiaSergienko) [reply src/test/java/com/exasol/adapter/document/DynamodbVsExasolTestDatabaseBuilder.java:36]: Create a ticket and change this behavior next time you touch that common module

Comment (jakobbraun) [reply src/test/java/com/exasol/adapter/document/DynamodbVsExasolTestDatabaseBuilder.java:36]: ok. https://github.com/exasol/virtual-schema-common-document/issues/17

File: src/test/java/com/exasol/adapter/document/DynamodbVsExasolTestDatabaseBuilder.java [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+     */
+    public void uploadDynamodbAdapterJar() throws InterruptedException, BucketAccessException, TimeoutException {
+        this.testInterface.uploadFileToBucketfs(PATH_TO_VIRTUAL_SCHEMAS_JAR, VIRTUAL_SCHEMAS_JAR_NAME_AND_VERSION);
+        uploadJacocoAgent();
+    }
+
+    public void createUdf() throws SQLException {// TODO make DynamoDB independent
+        final StringBuilder statementBuilder = new StringBuilder(
+                "CREATE OR REPLACE JAVA SET SCRIPT " + ADAPTER_SCHEMA + "." + UdfRequestDispatcher.UDF_PREFIX
+                        + "DYNAMO_DB" + "(" + AbstractDataLoaderUdf.PARAMETER_DOCUMENT_FETCHER + " VARCHAR(2000000), "
```
Comment (AnastasiiaSergienko) [inline src/test/java/com/exasol/adapter/document/DynamodbVsExasolTestDatabaseBuilder.java:33]: It will be more compact if you add a static import for the constants. But now it's human-readable :+1:

**Review by AnastasiiaSergienko — APPROVED** [review]
